# Generated by Django 4.0.2 on 2022-05-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='claim',
            fields=[
                ('claim_id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=50)),
                ('claim_source', models.CharField(max_length=50)),
                ('claim', models.CharField(max_length=50)),
                ('claim_publish_date', models.DateTimeField()),
                ('claim_receive_date', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('verdict', models.CharField(max_length=10)),
                ('media_type', models.CharField(max_length=20)),
                ('media_link_path', models.CharField(max_length=100)),
                ('claimant', models.CharField(max_length=20)),
                ('party', models.CharField(max_length=20)),
                ('topic', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=100)),
                ('source_link', models.CharField(max_length=100)),
                ('who_lodged_info', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=9)),
                ('checker_name', models.CharField(max_length=50)),
                ('verdict_simplified', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'claim',
            },
        ),
    ]
