# Generated by Django 4.0.2 on 2022-05-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim_app', '0002_alter_claim_checker_name_alter_claim_claim_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_source',
            field=models.CharField(blank=True, choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('Web', 'Web'), ('Email', 'Email'), ('YouTube', 'YouTube'), ('TikTok', 'TikTok')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='media_type',
            field=models.CharField(blank=True, choices=[('Video', 'Video'), ('Text', 'Text'), ('Audio', 'Audio'), ('Tweet', 'Tweet'), ('Pamphlet', 'Pamphlet')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='project',
            field=models.CharField(blank=True, choices=[('Facebook', 'Facebook'), ('Election', 'Election'), ('Climate', 'Climate'), ('Tipline', 'Tipline')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(blank=True, choices=[('Checked', 'Checked'), ('Unchecked', 'Unchecked')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='verdict',
            field=models.CharField(blank=True, choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE'), ('UNKNOWN', 'UNKNOWN')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='verdict_simplified',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('In_Between', 'In_Between')], max_length=10, null=True),
        ),
    ]
